// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.ts - DO NOT EDIT MANUALLY

// re-export TS/JS modules from this folder
export * from './theme.js';
export * from './types.js';

// default exports for components in this folder
export { default as Avatar } from './Avatar.svelte';
export { default as ThemeSettings } from './ThemeSettings.svelte';
export { default as ThemeSwitcher } from './ThemeSwitcher.svelte';
