// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.ts - DO NOT EDIT MANUALLY

// folder re-exports (export everything from these folders)
export * from "./body/index.js";
export * from "./display/index.js";
export * from "./headline/index.js";
export * from "./kbd/index.js";
export * from "./label/index.js";
export * from "./title/index.js";
