// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.ts - DO NOT EDIT MANUALLY

// re-export TS/JS modules from this folder
export * from "./theme.js";
export * from "./types.js";

// default exports for components in this folder
export { default as Tab } from "./Tab.svelte";
export { default as TabContent } from "./TabContent.svelte";
export { default as TabHolder } from "./TabHolder.svelte";
