/*
  Generates two files from Google's Material Symbols metadata:
  - src/lib/utils/icon/icon-names.ts: the `MaterialSymbolName` union, so `<Icon name>` rejects
    typos at type-check time. It comes from the font's own codepoints file, which lists every
    ligature the font renders, including deprecated aliases such as `smartphone` that the
    metadata marks unsupported but that still resolve. All three styles share the same set.
  - src/routes/guides/icons/catalog.json: the Icons guide playground's list, every symbol as
    [name, category], most popular first. Names only (no search tags), so it stays ~110 KB.
  Re-run when Google adds symbols:

    bun run generate:icons

  Runs on every push (lefthook.yml), which fails if either file changed.
*/
import { writeFileSync } from 'node:fs';

type Meta = {
  icons: {
    name: string;
    popularity: number;
    categories: string[];
    unsupported_families: string[];
  }[];
};

// Fails instead of writing empty files when a download breaks.
const download = async (url: string) => {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${url}`);
  return res.text();
};

const metadata = await download(
  'https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true'
);
// The response starts with an anti-JSON-hijacking prefix: )]}'
const meta: Meta = JSON.parse(metadata.replace(/^\)\]\}'/, ''));

const catalog = meta.icons
  .filter((icon) => !icon.unsupported_families.includes('Material Symbols Rounded'))
  .sort((a, b) => b.popularity - a.popularity || a.name.localeCompare(b.name))
  .map((icon) => [icon.name, icon.categories[0] ?? 'Other']);

const codepoints = await download(
  'https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/MaterialSymbolsRounded%5BFILL,GRAD,opsz,wght%5D.codepoints'
);
const names = [...new Set(codepoints.split('\n').map((line) => line.split(' ')[0]))]
  .filter(Boolean)
  .sort();
if (catalog.length < 1000 || names.length < 1000) {
  throw new Error(`Suspiciously few icons (${catalog.length} / ${names.length}); not writing.`);
}
writeFileSync('src/routes/guides/icons/catalog.json', JSON.stringify(catalog) + '\n');
writeFileSync(
  'src/lib/utils/icon/icon-names.ts',
  `// Generated by scripts/generate-icon-catalog.ts. Do not edit.

/** Every Material Symbols icon name (${names.length}). https://fonts.google.com/icons */
export type MaterialSymbolName =
${names.map((name) => `  | '${name}'`).join('\n')};
`
);
console.log(`${catalog.length} icons in the catalog, ${names.length} names in the type`);
