#!/usr/bin/env bun
import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();
const componentsDir = path.join(ROOT, 'src', 'lib', 'components');

function toPascalCase(name: string): string {
  return name
    .replace(/(^|[^a-zA-Z0-9]+)([a-zA-Z0-9])/g, (_, __, ch) => ch.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
}

async function generateDir(dir: string): Promise<void> {
  const entries = await fs.readdir(dir, { withFileTypes: true });

  const folders: string[] = [];
  const svelteFiles: string[] = [];
  const tsFiles: string[] = [];

  for (const e of entries) {
    if (e.isDirectory()) {
      if (e.name.startsWith('.')) continue;
      folders.push(e.name);
    } else if (e.isFile()) {
      if (e.name === 'index.ts') continue; // skip index files
      if (e.name.endsWith('.svelte')) svelteFiles.push(e.name);
      // include .ts/.js modules for barrel exports (exclude declaration files)
      else if ((e.name.endsWith('.ts') || e.name.endsWith('.js')) && !e.name.endsWith('.d.ts')) {
        tsFiles.push(e.name);
      }
    }
  }

  folders.sort((a, b) => a.localeCompare(b));
  svelteFiles.sort((a, b) => a.localeCompare(b));
  tsFiles.sort((a, b) => a.localeCompare(b));

  const outFile = path.join(dir, 'index.ts');

  const lines: string[] = [];
  lines.push(
    '// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.ts - DO NOT EDIT MANUALLY\n'
  );

  if (folders.length) {
    lines.push('// folder re-exports (export everything from these folders)');
    for (const f of folders) {
      lines.push(`export * from "./${f}/index.js";`);
    }
    lines.push('');
  }

  if (tsFiles.length) {
    lines.push('// re-export TS/JS modules from this folder');
    for (const file of tsFiles) {
      const base = path.basename(file, path.extname(file));
      lines.push(`export * from "./${base}.js";`);
    }
    lines.push('');
  }

  if (svelteFiles.length) {
    lines.push('// default exports for components in this folder');
    for (const file of svelteFiles) {
      const base = path.basename(file, '.svelte');
      const name = toPascalCase(base);
      lines.push(`export { default as ${name} } from "./${file}";`);
    }
    lines.push('');
  }

  const content = lines.join('\n') + '\n';
  await fs.writeFile(outFile, content, 'utf8');
  console.log(
    `Generated ${path.relative(ROOT, outFile)} (folders: ${folders.length}, svelte: ${svelteFiles.length}, modules: ${tsFiles.length})`
  );

  // Recurse into folders
  for (const f of folders) {
    await generateDir(path.join(dir, f));
  }
}

async function main(): Promise<void> {
  try {
    await generateDir(componentsDir);
  } catch (err) {
    console.error('Failed to generate components index:', err);
    process.exitCode = 1;
  }
}

main();
