// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.ts - DO NOT EDIT MANUALLY

// default exports for components in this folder
export { default as InputMerger } from "./InputMerger.svelte";
